### ISSUE TITLE
Implementar nome do usuário pesquisado na query 

### ISSUE THREAD

**Issue by ValdielsonSiqueira** [kelisonrosendo/github-repos#10]
Título da Issue:
Implementar nome do usuário pesquisado na query 

Descrição:
Implementar nome do usuário na query, para recuperação da visão.

**Comment by kelisonrosendo** [comment]
@ValdielsonSiqueira, foi implementado na branch linkada aqui :smile:

**Comment by ValdielsonSiqueira** [comment]
Sananagem! Quando for subir, conclui a issue então 0/
